name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: goalblink_handbook.tex
          pre_compile: "fc-list :lang=zh"
          latexmk_use_xelatex: true
      - name: Commit PDF to main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add goalblink_handbook.pdf
          git commit -m "自动更新 handbook PDF [ci skip]" || echo "No changes to commit"
          git push origin main