name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: goalblink_handbook.tex
          pre_compile: "fc-list :lang=zh"
          latexmk_use_xelatex: true
      - name: Release PDF
        uses: softprops/action-gh-release@v2
        with:
          files: goalblink_handbook.pdf